{"name": "Try Signup With Invalid Password", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestsSignup' object has no attribute 'goto'", "trace": "page = <tests.test_auth.TestsSignup object at 0x0000027B855715B0>\n\n    @allure.story(\"Попытка регистрации под невалидным паролем\")\n    def test_try_signup_with_invalid_password(page: Page):\n>       page.goto(f\"{base_auth_url}register\")\n        ^^^^^^^^^\nE       AttributeError: 'TestsSignup' object has no attribute 'goto'\n\ntests\\test_auth.py:98: AttributeError"}, "start": 1751800039737, "stop": 1751800039737, "uuid": "a103a509-a39b-42d9-b9eb-514464239a76", "historyId": "4d9e328e7189abeda65d4e238ee0c25d", "testCaseId": "4d9e328e7189abeda65d4e238ee0c25d", "fullName": "tests.test_auth.TestsSignup#test_try_signup_with_invalid_password", "labels": [{"name": "feature", "value": "Регистрация"}, {"name": "story", "value": "Попытка регистрации под невалидным паролем"}, {"name": "epic", "value": "Форма регистрации"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestsSignup"}, {"name": "host", "value": "WIN-V8TQK9SAURU"}, {"name": "thread", "value": "4052-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}